### ISSUE TITLE
Extension icon unremovable

### ISSUE THREAD

**Issue by ShalokShalom** [xplosionmind/firefox-monoline#12]
Hi there 👍🏻 

You write, that I should remove all icons. 
The new extension icon, probably not included at the point of writing, cannot be removed. 

![Screenshot_20230910_213530](https://github.com/xplosionmind/firefox-monoline/assets/6344099/b72b2d6b-9d44-4281-bb1a-b00eb3471eb2)

**Comment by xplosionmind** [comment]
Thanks for the feedback, @ShalokShalom! I need to properly get into the last ~5 Firefox versions since I am using another theme and not this one currently, therefore this repository is not being very maintained. I am thinking about switching back to firefox-monoline and address this and other issues. Hence, I am reopening this issue.

**Comment by ShalokShalom** [comment]
I did split the compact and the large version into separate CSS files. 
https://github.com/ShalokShalom/firefox-monoline

**Comment by ShalokShalom** [comment]
And in case you want to know, that it works for me on newest Firefox:

![Screenshot_20230913_011712](https://github.com/xplosionmind/firefox-monoline/assets/6344099/e3041bcf-1447-40c8-ace4-f706a3e62dbf)

**Comment by xplosionmind** [comment]
[v1.2](https://github.com/xplosionmind/firefox-monoline/releases/tag/v1.2) handles the unified extensions button, and shows in a comment how to completely remove it.
